.\" Manpage for zypper-lifecycle.
.TH man 8 "18 Apr 2016" "1.0" "zypper-lifecycle man page"
.SH NAME
zypper-lifecycle \- products and packages lifecycle information
.SH SYNOPSIS
zypper lifecycle [ -v | --verbose ] [--save <file>] [ --diff <file> ] --days N | --date <date> | <package> ...
.SH DESCRIPTION
zypper-lifecycle shows an overview of products and packages lifecycle
.SH OPTIONS
.TP
.B --days N
Show packages/products whose support ends in N days (from now)
.TP
.B --date YYYY-MM-DD
Show packages/products whose support ends before the specified date
.TP
.B  --save <file>
Save report to a file in machine-readable form. This file can be later used for --diff option.
.TP
.B  --diff <file>
Report only differences from previouly saved report. This option can't be used
together with explicit package names.
.TP
.B  -v, --[no-]verbose
Run verbosely
.SH RETURN VALUE
zypper lifecycle returns 0 on success, 1 if some of queried packages are not installed or if
the report is empty and 2 on other errors.
.SH SEE ALSO
zypper(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Vladimir Nadvornik <nadvornik@suse.cz>
